version: "3"

services:

  backend:
    build:
      context: backend
      args:
        ANTIPLAGIAT_PORT: 8088
        ANTIPLAGIAT_DIR: /opt/antiplagiat/backend
    depends_on:
      - db
    environment:
      - ANTIPLAGIAT_DB_HOST=db:27017/
      - ANTIPLAGIAT_PORT=8088
      - ANTIPLAGIAT_DB_NAME=antiplagiat
      - ANTIPLAGIAT_DIR=/opt/antiplagiat_backend
      - ANTIPLAGIAT_REPOS_DIR=/opt/antiplagiat_backend/repos
    command: backend
    ports:
      - "8088:8088"

  db:
    image: "mongo:7.0.2"
    restart: always
    ports:
      - 27077:27017
